name: Docker Workflow

on:
  push:
    branches:
      - main
env:
  UNITY_IMAGE: "docker://alpine:latest"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Docker container
        uses: UNITY_IMAGE
        with:
          args: echo "Hello, Docker!"
