name: Build - CI

on:
 workflow_dispatch:

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Set up Docker
        run: |
            docker pull unityci/editor:ubuntu-2022.3.29f1-windows-mono-3
      - name: Activate Unity License
        run: |
            mkdir -p /home/runner/.cache/unity3d
            echo "${{ secrets.UNITY_LICENSE }}" | tr -d '\r' > ./Unity_lic.ulf
            if [ -f /home/runner/.cache/unity3d/Unity_lic.ulf ]; then
              echo "Unity license file created successfully."
            else
              echo "Failed to create Unity license file." >&2
            exit 1
            fi
        shell: bash
      - name: Build with Docker
        run: |
          docker run --rm \
          -v $(pwd):/project \
          -w /project \
          unityci/editor:ubuntu-2022.3.29f1-windows-mono-3 \
          /bin/bash -c "unity-editor -batchmode -nographics -quit -projectPath /project -buildTarget StandaloneLinux64 -executeMethod BuildCommand.PerformBuild"
      - name: Deactivate Unity License
        run: rm /home/runner/.cache/unity3d/Unity_lic.ulf
        shell: bash
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build
