name: Build - CI

on:
 workflow_dispatch:

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Set up Docker
        run: |
          docker pull unityci/editor:ubuntu-2022.3.29f1-windows-mono-3
      - name:
        run: |
          set -e
          set -x
          mkdir -p /root/.cache/unity3d
          mkdir -p /root/.local/share/unity3d/Unity/
          set +x
          echo 'Writing $UNITY_LICENSE_CONTENT to license file /root/.local/share/unity3d/Unity/Unity_lic.ulf'
          echo "$UNITY_LICENSE_CONTENT" | base64 --decode | tr -d '\r' > /root/.local/share/unity3d/Unity/Unity_lic.ulf
      - name: Build with Docker
        run: |
          docker run --rm \
          -v $(pwd):/project \
          -w /project \
          unityci/editor:ubuntu-2022.3.29f1-windows-mono-3 \
          /bin/bash -c "unity-editor -batchmode -nographics -quit -projectPath /project -buildTarget StandaloneLinux64 -executeMethod BuildCommand.PerformBuild"
  
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build