name: accion
on:
  push:
    branches:
      - main
jobs:
  mi_trabajo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2
      - name: Prueba
        run: |
          echo "Hola, mundo!"
